name: poc_pdf
description: "PoC PDF"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: 3.5.3

dependencies:
  flutter:
    sdk: flutter
  open_file: 3.5.7
  path_provider: 2.1.4
  pdf: 3.11.1
  permission_handler: 11.3.1
  universal_html: 2.2.4

dev_dependencies:
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bola.jpg
