name: poc_pdf
description: "PoC PDF"
publish_to: 'none'

version: 1.0.0

environment:
  sdk: 3.5.3

dependencies:
  flutter:
    sdk: flutter
  permission_handler: 11.3.1

dev_dependencies:
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
